// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKYIOrDwFDQPWPpp4GneJlMNVrX1sSxog',
    appId: '1:222684621681:web:a0ab9355fed8a1bb1b24d0',
    messagingSenderId: '222684621681',
    projectId: 'chatt-app-cafbe',
    authDomain: 'chatt-app-cafbe.firebaseapp.com',
    storageBucket: 'chatt-app-cafbe.appspot.com',
    measurementId: 'G-ZFW4WD0JH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwfkSUt1q_Zj-DEeID2GzRGOuaw0J4grs',
    appId: '1:222684621681:android:9f6911e3b135a2301b24d0',
    messagingSenderId: '222684621681',
    projectId: 'chatt-app-cafbe',
    storageBucket: 'chatt-app-cafbe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZAlGgyVEErOKtk2A_kIm7qQJjBOsKXzc',
    appId: '1:222684621681:ios:8f2fbb480b5c3e111b24d0',
    messagingSenderId: '222684621681',
    projectId: 'chatt-app-cafbe',
    storageBucket: 'chatt-app-cafbe.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZAlGgyVEErOKtk2A_kIm7qQJjBOsKXzc',
    appId: '1:222684621681:ios:8f2fbb480b5c3e111b24d0',
    messagingSenderId: '222684621681',
    projectId: 'chatt-app-cafbe',
    storageBucket: 'chatt-app-cafbe.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKYIOrDwFDQPWPpp4GneJlMNVrX1sSxog',
    appId: '1:222684621681:web:a9333b00b0941dce1b24d0',
    messagingSenderId: '222684621681',
    projectId: 'chatt-app-cafbe',
    authDomain: 'chatt-app-cafbe.firebaseapp.com',
    storageBucket: 'chatt-app-cafbe.appspot.com',
    measurementId: 'G-TS76J53DGG',
  );
}
